/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ClienteControlador;
import Controlador.CompraControlador;
import Controlador.InmuebleControlador;
import Controlador.PagoControlador;
import Controlador.VendedorControlador;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {
    public static JDesktopPane jDesktopPane_menu;
    private ClienteControlador clienteControlador;
    private VendedorControlador vendedorControlador;
    private CompraControlador compraControlador;
    private InmuebleControlador inmuebleControlador;
    private PagoControlador pagoControlador;
    /**
     * 
     * Creates new form men
     */
    public Menu() {
        initComponents();
        clienteControlador= new ClienteControlador();
        compraControlador = new CompraControlador();
        inmuebleControlador = new InmuebleControlador();
        vendedorControlador = new VendedorControlador();
        pagoControlador = new PagoControlador();
        this.setSize(new Dimension(1050,250));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Inmobiliaria");
        
        
        this.setLayout(null);
        jDesktopPane_menu= new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuclientes = new javax.swing.JMenu();
        mgestioncliente = new javax.swing.JMenuItem();
        menuinmuebles = new javax.swing.JMenu();
        minmueble = new javax.swing.JMenuItem();
        menuregistrarventa = new javax.swing.JMenu();
        mgestioncompra = new javax.swing.JMenuItem();
        menuvendedor = new javax.swing.JMenu();
        mvendedor = new javax.swing.JMenuItem();
        menupagos = new javax.swing.JMenu();
        mpagos = new javax.swing.JMenuItem();
        menusalir = new javax.swing.JMenu();
        msalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente_1.png"))); // NOI18N
        menuclientes.setText("Menú Clientes");
        menuclientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuclientes.setPreferredSize(new java.awt.Dimension(150, 50));

        mgestioncliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mgestioncliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuraciones.png"))); // NOI18N
        mgestioncliente.setText("Gestión Clientes");
        mgestioncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgestionclienteActionPerformed(evt);
            }
        });
        menuclientes.add(mgestioncliente);

        jMenuBar1.add(menuclientes);

        menuinmuebles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa (2).png"))); // NOI18N
        menuinmuebles.setText("Menú Inmuebles");
        menuinmuebles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuinmuebles.setPreferredSize(new java.awt.Dimension(180, 50));

        minmueble.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minmueble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuraciones.png"))); // NOI18N
        minmueble.setText("Gestión Inmuebles");
        minmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minmuebleActionPerformed(evt);
            }
        });
        menuinmuebles.add(minmueble);

        jMenuBar1.add(menuinmuebles);

        menuregistrarventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito_1.png"))); // NOI18N
        menuregistrarventa.setText("Registro de Ventas Inmobiliaria ");
        menuregistrarventa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuregistrarventa.setMinimumSize(new java.awt.Dimension(150, 50));
        menuregistrarventa.setPreferredSize(new java.awt.Dimension(260, 50));

        mgestioncompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mgestioncompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuraciones.png"))); // NOI18N
        mgestioncompra.setText("Gestionar Compra");
        mgestioncompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgestioncompraActionPerformed(evt);
            }
        });
        menuregistrarventa.add(mgestioncompra);

        jMenuBar1.add(menuregistrarventa);

        menuvendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        menuvendedor.setText("Menú Vendedor");
        menuvendedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuvendedor.setPreferredSize(new java.awt.Dimension(160, 50));

        mvendedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mvendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo_1.png"))); // NOI18N
        mvendedor.setText("Registrar Vendedor");
        mvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvendedorActionPerformed(evt);
            }
        });
        menuvendedor.add(mvendedor);

        jMenuBar1.add(menuvendedor);

        menupagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial1.png"))); // NOI18N
        menupagos.setText("Menu Pagos");
        menupagos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menupagos.setPreferredSize(new java.awt.Dimension(150, 50));

        mpagos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mpagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/historial1.png"))); // NOI18N
        mpagos.setText("Historial de Pagos");
        mpagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpagosActionPerformed(evt);
            }
        });
        menupagos.add(mpagos);

        jMenuBar1.add(menupagos);

        menusalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        menusalir.setText("Cerrar Sesión");
        menusalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menusalir.setPreferredSize(new java.awt.Dimension(150, 50));

        msalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        msalir.setText("Salir");
        msalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msalirActionPerformed(evt);
            }
        });
        menusalir.add(msalir);

        jMenuBar1.add(menusalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvendedorActionPerformed
        this.dispose();
        JFrame vendedorFrame = new JFrame("Vendedor");
        
        // Crear la instancia de GestionClientes y agregarla como observador
        GestionClientes gestionClientes = new GestionClientes();
        vendedorControlador.agregarObservador(gestionClientes);
        vendedorControlador.entrarVista();
        
        vendedorFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        vendedorFrame.add(new GestionVendedor()); // Añadir el panel de la nueva propiedad
        vendedorFrame.pack(); // Ajustar tamaño al contenido
        vendedorFrame.setLocationRelativeTo(null); // Centrar la ventana en pantalla
        vendedorFrame.setVisible(true);
    }//GEN-LAST:event_mvendedorActionPerformed

    private void mpagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpagosActionPerformed
        this.dispose();
        JFrame pagoFrame = new JFrame("Pagos");
        
        // Crear la instancia de GestionClientes y agregarla como observador
        GestionClientes gestionClientes = new GestionClientes();
        pagoControlador.agregarObservador(gestionClientes);
        pagoControlador.entrarVista();
        
        pagoFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        pagoFrame.add(new HistorialPagos()); // Añadir el panel de la nueva propiedad
        pagoFrame.pack(); // Ajustar tamaño al contenido
        pagoFrame.setLocationRelativeTo(null); // Centrar la ventana en pantalla
        pagoFrame.setVisible(true);
    }//GEN-LAST:event_mpagosActionPerformed

    private void msalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_msalirActionPerformed

    private void mgestionclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgestionclienteActionPerformed
        this.dispose();
        JFrame clienteFrame = new JFrame("Clientes");
        clienteFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        
        // Crear la instancia de GestionClientes y agregarla como observador
        GestionClientes gestionClientes = new GestionClientes();
        clienteControlador.agregarObservador(gestionClientes);
        // Notificar a los observadores sobre la entrada a la vista
        clienteControlador.entrarVista();
        
        clienteFrame.add(new GestionClientes()); // Añadir el panel de la nueva propiedad
        clienteFrame.pack(); // Ajustar tamaño al contenido
        clienteFrame.setLocationRelativeTo(null); // Centrar la ventana en pantalla
        clienteFrame.setVisible(true);
    }//GEN-LAST:event_mgestionclienteActionPerformed

    private void minmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minmuebleActionPerformed
        this.dispose();
        JFrame propiedadFrame = new JFrame("Inmuebles");
        
        // Crear la instancia de GestionClientes y agregarla como observador
        GestionClientes gestionClientes = new GestionClientes();
        inmuebleControlador.agregarObservador(gestionClientes);
        inmuebleControlador.entrarVista();
        
        propiedadFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        propiedadFrame.add(new GestionPropiedad()); // Añadir el panel de la nueva propiedad
        propiedadFrame.pack(); // Ajustar tamaño al contenido
        propiedadFrame.setLocationRelativeTo(null); // Centrar la ventana en pantalla
        propiedadFrame.setVisible(true);
            
    }//GEN-LAST:event_minmuebleActionPerformed

    private void mgestioncompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgestioncompraActionPerformed
        this.dispose();
        JFrame compraFrame = new JFrame("Ventas");
        
        // Crear la instancia de GestionClientes y agregarla como observador
        GestionClientes gestionClientes = new GestionClientes();
        compraControlador.agregarObservador(gestionClientes);
        compraControlador.entrarVista();
        
        compraFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Solo cerrar esta ventana
        compraFrame.add(new GestionCompra()); // Añadir el panel de la nueva propiedad
        compraFrame.pack(); // Ajustar tamaño al contenido
        compraFrame.setLocationRelativeTo(null); // Centrar la ventana en pantalla
        compraFrame.setVisible(true);
    }//GEN-LAST:event_mgestioncompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuclientes;
    private javax.swing.JMenu menuinmuebles;
    private javax.swing.JMenu menupagos;
    private javax.swing.JMenu menuregistrarventa;
    private javax.swing.JMenu menusalir;
    private javax.swing.JMenu menuvendedor;
    private javax.swing.JMenuItem mgestioncliente;
    private javax.swing.JMenuItem mgestioncompra;
    private javax.swing.JMenuItem minmueble;
    private javax.swing.JMenuItem mpagos;
    private javax.swing.JMenuItem msalir;
    private javax.swing.JMenuItem mvendedor;
    // End of variables declaration//GEN-END:variables
}
